// File generated by FlutterFire — replace values with `flutterfire configure` for FCM.
// ignore_for_file: lines_longer_than_80_chars

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Placeholder Firebase options so the app compiles without google-services.json.
/// Push delivery requires a real Firebase project.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => android;

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyPlaceholderConfigureFlutterFireKpms',
    appId: '1:000000000000:android:0000000000000000placeholder',
    messagingSenderId: '000000000000',
    projectId: 'kpms-notifications-placeholder',
    storageBucket: 'kpms-notifications-placeholder.appspot.com',
  );
}
